services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: alumninominations
      POSTGRES_USER: alumni
      POSTGRES_PASSWORD: secpass
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && node dist/src/main.js"


networks:
  bridge: {}

volumes:
  pgdata:
