version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: alumninomination
    restart: always
    environment:
      POSTGRES_USER: alumni
      POSTGRES_PASSWORD: secpass
      POSTGRES_DB: alumninomination
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./
    container_name: nest_backend2
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://alumni:secpass@postgres:5432/alumninomination
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    command: >
      sh -c "until pg_isready -h postgres -p 5432; do sleep 2; done &&
      npx prisma migrate deploy &&
      yarn start"

volumes:
  postgres_data: